const ActionTypes = {
    SIGNUP_REQUEST : 'SIGNUP_REQUEST',
    SIGNUP_REQUEST_SUCCESS : 'SIGNUP_REQUEST_SUCCESS',

    LOGIN_REQUEST : 'LOGIN_REQUEST',
    LOGIN_REQUEST_SUCCESS : 'LOGIN_REQUEST_SUCCESS',
    QUESTION_REQUEST : 'QUESTION_REQUEST',
    QUESTION_REQUEST_SUCCESS : 'QUESTION_REQUEST_SUCCESS',
    VIEW_USER_DETAIL_REQUEST : 'VIEW_USER_DETAIL_REQUEST',
    VIEW_USER_DETAIL_REQUEST_SUCCESS:'VIEW_USER_DETAIL_REQUEST_SUCCESS'
}

export default ActionTypes;